language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO_VERSION=""
  - DJANGO_VERSION=">=1.11,<2"
  - DJANGO_VERSION=">=2,<2.1"
  - DJANGO_VERSION=">=2.1,<2.2"
  - DJANGO_VERSION=">=2.2,<3"
  - DJANGO_VERSION=">=3,<3.1"
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO_VERSION=">=3,<3.1"
install:
  - pip install codecov $([ -n "$DJANGO_VERSION" ] && echo "Django$DJANGO_VERSION")
script:
  - if [ -n "$DJANGO_VERSION" ]; then
      coverage run --source=optimize_later testproject/manage.py test;
    else
      coverage run --source=optimize_later -m unittest discover optimize_later/;
    fi
after_script:
  - codecov
